"""
Praxeology MCP — Heartbeat engine.

Two-tier background check system:
    Tier 1: Lightweight rule-based check (no LLM, cost = 0)
    Tier 2: Heavyweight trigger — logs event, placeholder for LLM invocation
"""

from __future__ import annotations

import threading
import time
from datetime import datetime, timezone
from pathlib import Path

from praxeology_mcp.db import get_config, get_db, log_metric


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class Heartbeat:
    def __init__(self, db_path: str, interval: int = 300):
        self.db_path = db_path
        self.interval = interval
        self._running = False
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        """Start heartbeat as daemon thread."""
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._running = False

    def _loop(self) -> None:
        while self._running:
            result = self.lightweight_check()
            if result["needs_attention"]:
                self.heavyweight_trigger(result["reasons"])
            self._stop_event.wait(timeout=self.interval)

    def lightweight_check(self) -> dict:
        """Rule-based check. No LLM. Cost = 0.

        Returns:
            {"needs_attention": bool, "reasons": list[str]}
        """
        reasons: list[str] = []
        conn = get_db(self.db_path)
        try:
            # Check 1: pending work items in objectives
            row = conn.execute(
                "SELECT COUNT(*) AS cnt FROM objectives WHERE status = 'pending'"
            ).fetchone()
            if row and row["cnt"] > 0:
                reasons.append(f"pending_objectives: {row['cnt']} pending work item(s)")

            # Check 2: overdue schedules (next_run < now, enabled = 1)
            now_iso = _utcnow_iso()
            row = conn.execute(
                "SELECT COUNT(*) AS cnt FROM schedules"
                " WHERE enabled = 1 AND next_run IS NOT NULL AND next_run < ?",
                (now_iso,),
            ).fetchone()
            if row and row["cnt"] > 0:
                reasons.append(f"overdue_schedules: {row['cnt']} overdue schedule(s)")

            # Check 3: open gaps with frequency > 3
            row = conn.execute(
                "SELECT COUNT(*) AS cnt FROM gaps"
                " WHERE status = 'open' AND frequency > 3"
            ).fetchone()
            if row and row["cnt"] > 0:
                reasons.append(f"high_frequency_gaps: {row['cnt']} open gap(s) with frequency > 3")

            # Check 4: unread delegations with status = 'pending'
            row = conn.execute(
                "SELECT COUNT(*) AS cnt FROM delegations WHERE status = 'pending'"
            ).fetchone()
            if row and row["cnt"] > 0:
                reasons.append(f"pending_delegations: {row['cnt']} unread delegation(s)")

        except Exception as exc:
            return {"needs_attention": False, "error": str(exc)}

        return {"needs_attention": bool(reasons), "reasons": reasons}

    def heavyweight_trigger(self, reasons: list) -> dict:
        """Evaluate whether LLM action is needed based on accumulated signals."""
        conn = get_db(self.db_path)
        try:
            # Count pending gaps with high frequency (>= 3)
            urgent_gaps = conn.execute(
                "SELECT COUNT(*) FROM gaps WHERE status = 'open' AND frequency >= 3"
            ).fetchone()[0]

            # Count overdue work items
            overdue_work = conn.execute(
                "SELECT COUNT(*) FROM objectives WHERE tier = 'work' AND status = 'pending'"
                " AND due_date < date('now') AND due_date != ''"
            ).fetchone()[0]

            # Count unhandled delegations
            pending_delegations = conn.execute(
                "SELECT COUNT(*) FROM delegations WHERE status = 'pending'"
            ).fetchone()[0]

            # Decision: if any urgent signal exists, log for LLM attention
            priority_score = urgent_gaps * 3 + overdue_work * 2 + pending_delegations * 1

            if priority_score >= 5:
                # High priority — would trigger LLM in production
                # For now, create a placeholder work item for human attention
                existing = conn.execute(
                    "SELECT id FROM objectives WHERE title LIKE '[Heartbeat]%' AND status = 'pending'"
                ).fetchone()
                if existing is None:
                    conn.execute(
                        "INSERT INTO objectives (tier, title, description, status, priority) VALUES (?, ?, ?, ?, ?)",
                        ("work", f"[Heartbeat] Review {urgent_gaps} urgent gaps + {overdue_work} overdue items",
                         f"Auto-generated by heartbeat. Priority score: {priority_score}. Reasons: {', '.join(reasons)}",
                         "pending", "high")
                    )
                    conn.commit()

            # Send Discord webhook if configured
            webhook_url = get_config(conn, "discord_webhook")
            if webhook_url and priority_score >= 5:
                self._send_discord_alert(webhook_url, priority_score, urgent_gaps, overdue_work, pending_delegations, reasons)

            log_metric(conn, "heartbeat.heavyweight_trigger", "cross",
                       tokens=0, latency=0)

            # Store trigger result for dashboard consumption
            conn.execute(
                "INSERT INTO metrics_log (tool_name, axis, tokens_used, latency_ms) VALUES (?, ?, ?, ?)",
                (f"heartbeat.trigger.priority_{priority_score}", "cross", 0, 0),
            )
            conn.commit()

            return {
                "triggered": True,
                "priority_score": priority_score,
                "urgent_gaps": urgent_gaps,
                "overdue_work": overdue_work,
                "pending_delegations": pending_delegations,
                "reasons": reasons,
            }
        except Exception as exc:
            return {"error": str(exc)}

    def _send_discord_alert(self, webhook_url: str, score: int, gaps: int, overdue: int, delegations: int, reasons: list) -> None:
        """Send alert to Discord via webhook."""
        import json
        import urllib.request

        message = {
            "content": None,
            "embeds": [{
                "title": "Praxeology Heartbeat Alert",
                "description": f"Priority score: **{score}** — action needed.",
                "color": 0xD4A843,  # gold
                "fields": [
                    {"name": "Urgent Gaps", "value": str(gaps), "inline": True},
                    {"name": "Overdue Work", "value": str(overdue), "inline": True},
                    {"name": "Pending Delegations", "value": str(delegations), "inline": True},
                    {"name": "Reasons", "value": "\n".join(f"• {r}" for r in reasons[:5]) or "—"},
                ],
            }]
        }

        try:
            req = urllib.request.Request(
                webhook_url,
                data=json.dumps(message).encode(),
                headers={"Content-Type": "application/json"},
            )
            resp = urllib.request.urlopen(req, timeout=5)
            status = resp.getcode()
            if status not in (200, 204):
                # Non-success — log it
                from praxeology_mcp.db import get_db, log_metric
                conn = get_db(self.db_path)
                log_metric(conn, f"heartbeat.webhook_http_{status}", "cross", tokens_used=0, latency_ms=0)
        except Exception as exc:
            # Log webhook error to metrics (daemon has no stderr)
            try:
                from praxeology_mcp.db import get_db, log_metric
                conn = get_db(self.db_path)
                log_metric(conn, "heartbeat.webhook_error", "cross", tokens_used=0, latency_ms=0)
            except Exception:
                pass  # Last resort — don't crash heartbeat

    def check_once(self) -> dict:
        """Manual single check (for CLI/testing)."""
        return self.lightweight_check()


def run_daemon(db_path: str = None, interval: int = 300):
    """Entry point for daemon mode. Called by DaemonManager."""
    if db_path is None:
        db_path = str(Path.home() / ".claude" / "praxeology" / "praxeology.db")
    from praxeology_mcp.db import init_db
    init_db(db_path)
    hb = Heartbeat(db_path, interval=interval)

    import signal
    def handle_sigterm(signum, frame):
        hb._running = False
        hb._stop_event.set()
    signal.signal(signal.SIGTERM, handle_sigterm)

    hb._running = True
    hb._loop()
